### PR TITLE
Webhook support and sundries.

### PR DESCRIPTION
**Pull request by rebeccacremona**
## New Feature

This PR adds support for webhook notifications: when requesting a capture, a user may optionally supply a list of callback URLs they wish to be notified when the capture is complete. They may optionally include a key and algorithm with which to sign the `POST`ed data, and may optionally include an arbitrary string of data for their own use, to be included in the notification.

The optional signature can be used upstream to verify that `POST`s to the callback are indeed from us, in the absence of other authentication or special networking setups.

The optional user data field makes it easier to integrate this application with users' existing workflows. For instance, I set up a zap in Zapier that triggers a capture request whenever a user takes certain actions in Slack. The user data field lets me pass the id of the triggering Slack message along with the request, so that the callback (another zap) can then post the WACZ as a threaded reply.

Pending further discussion about design, I did not add any retry logic at this time.

## Documentation

Then I went to town enhancing the auto-generated documentation for the API by more fully utilizing FastAPI/Pydantic features. (Since I was doing it for the webhooks, I figured why not do everything at once.)

What that looks like: 
- stricter types and additional validation on input (some of which just documents, some of which prevents internal server errors)
- lots of titles/descriptions/examples
- pydantic models for responses as well as requests, so that the docs tell users what to expect back, as well as what to supply

That documentation exercise led to a bit of...

## Minor Refactoring

The new docs made it easy to spot that we could be sending more RESTful response codes:
- Successfully creating new capture jobs returns 201 instead of 200.
- Successfully deleting a capture job returns 204 instead of 200.
- Attempting to delete a non-existent capture job returns 404 instead of 200.
- Attempting to delete a capture job with the wrong userid returns 403 instead of 200.

These tweaks to response codes will necessitate a quick [corresponding update to the UI](https://github.com/webrecorder/kubecaptures-ui/pull/5).

The move to Pydantic models also made it possible to tighten up syntax in a couple places (for instance, in formatting datetimes).

## Home Page

I think the ReDoc docs are actually much nicer than the Swagger docs, though I can see why not all would agree.... So, I added a link to both on the home page.

~And, I dug into why the JS UI was not loading, and why the `main` image couldn't be built as-is: this was just never fully migrated during the big refactor that split the repos. I cleaned up the Dockerfile, added a service worker at `/replay`, and, for now, linked to the built JS hosted at `capture.perma.cc` and the service worker at `https://cdn.jsdelivr.net/npm/replaywebpage@1.1.2/sw.js"`, to go accompany the already-present `<script src="https://replayweb.page/ui.js"></script>`. That wants to be set by config in the future, of course: I'll work on that in a forthcoming PR to the upstream Browserkube repo.~

I can't verify that playback on the index page is working locally because there's still some work to do with minio re: storageUrl, accessUrl, and signed urls.... but that's a project for later.

### CODE REVIEW

**Comment by rebeccacremona** [comment]
image

**Comment by rebeccacremona** [comment]
image

**Comment by rebeccacremona** [comment]
@ikreymer Alrighty, I finally rebased this on `main` and adapted it for your strategy of bundling in the compiled JS: there are no more merge conflicts, unless you have other commits planned :-) If possible, I really love to see this (and therefore the PRs dependent on it) merged this week, so I can finish up my Zapier demo. Does that sound feasible to you? If you have concerns apart from the merge conflict, just holler.

**Comment by ikreymer** [comment]
Sorry for the delay! The new UI looks great, just testing now!

**Pull request merged**
